name: Publish to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2

    - name: Install Node.js dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Publish to GitHub Pages
      run: npx gh-pages -d dist
